# Generated by Django 2.0.5 on 2019-11-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a creatures name', max_length=20)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
